"""create places table

Revision ID: d7286e80dec4
Revises: 
Create Date: 2026-06-23 18:58:50.558802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7286e80dec4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('places',
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('place_type', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('source_ids', sa.JSON(), nullable=True),
    sa.Column('amenities', sa.JSON(), nullable=True),
    sa.Column('hours', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('place_id')
    )
    op.create_index(op.f('ix_places_lat'), 'places', ['lat'], unique=False)
    op.create_index(op.f('ix_places_lng'), 'places', ['lng'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_places_lng'), table_name='places')
    op.drop_index(op.f('ix_places_lat'), table_name='places')
    op.drop_table('places')
    # ### end Alembic commands ###
